# Generated by Django 4.1.7 on 2023-06-20 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='Lite', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('cstype', models.CharField(max_length=1000)),
                ('people_min', models.IntegerField()),
                ('people_max', models.IntegerField()),
                ('online_ticket', models.CharField(default='false', max_length=10)),
                ('sic', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('people', models.IntegerField()),
                ('cstype', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('waiting', models.IntegerField()),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nameid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price_sell', models.IntegerField()),
                ('price_buy', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('Images', models.ImageField(upload_to='')),
                ('is_active', models.CharField(max_length=50)),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.product')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ticket')),
            ],
        ),
    ]
