# Generated by Django 4.1.7 on 2023-07-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_shop_mail_massege_shop_online_auth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='mail_massege',
            new_name='email_massege',
        ),
    ]
