# Generated by Django 4.1.7 on 2023-07-24 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_product_id_cellproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellproduct',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.shop'),
            preserve_default=False,
        ),
    ]
