# Generated by Django 4.1.7 on 2023-07-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_cellproduct_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellproduct',
            name='day',
            field=models.CharField(default='2023-07-24', max_length=10),
            preserve_default=False,
        ),
    ]
