# Generated by Django 4.2.2 on 2023-06-21 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_usercontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontrol',
            name='permission',
        ),
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='market',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='shopconsole',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='ticket',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
