# Generated by Django 4.1.7 on 2023-06-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_usercontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontrol',
            name='permission',
        ),
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 20, 24, 27, 303025), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='market',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='shopconsole',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontrol',
            name='ticket',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
