# Generated by Django 4.1.7 on 2023-07-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_cellproduct_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='mail_massege',
            new_name='email_massege',
        ),
    ]
