# Generated by Django 4.1.7 on 2023-07-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_rename_mail_massege_shop_email_massege'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='regi_ticket',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
