# Generated by Django 4.1.7 on 2023-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_shop_regi_ticket_alter_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cs_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
