# Generated by Django 4.1.7 on 2023-07-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_order_cs_price_order_number_order_remaining_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='regi_post',
            field=models.URLField(blank=True),
        ),
    ]
