# Generated by Django 4.1.7 on 2023-07-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_shop_regi_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
