# Generated by Django 4.1.7 on 2023-07-31 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_virtualuser_remove_usercontrol_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shop',
            name='token',
            field=models.CharField(default='asdldfsdsd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
