# Generated by Django 4.1.7 on 2023-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_remove_virtualuser_is_active_shop_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='secret',
            field=models.CharField(default='asdfafs', max_length=50),
            preserve_default=False,
        ),
    ]
