# Generated by Django 4.1.7 on 2023-07-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_shop_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='regi_post',
            new_name='webhock',
        ),
    ]
