# Generated by Django 4.1.7 on 2023-08-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_product_images_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
