# Generated by Django 4.1.7 on 2023-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_rename_images_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='order_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='regi_pass',
            field=models.BooleanField(default=False),
        ),
    ]
