# Generated by Django 4.1.7 on 2023-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_remove_shop_message_shop_ucc_baner_shop_ucc_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email_massege',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='organization',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='people_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='people_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='regi_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
