# Generated by Django 4.1.7 on 2023-08-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_alter_shop_description_alter_shop_email_massege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limit',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ucc_baner',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ucc_resource',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ucc_ticket',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ucc_treasure',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
