# Generated by Django 4.1.7 on 2023-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_shop_market_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
