# Generated by Django 4.1.7 on 2023-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_alter_product_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='regi_post',
            field=models.BooleanField(default=False),
        ),
    ]
