# Generated by Django 4.1.7 on 2023-08-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_squashed_0029_alter_order_secret_alter_shop_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cellproduct',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cellproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shop'),
        ),
        migrations.AlterField(
            model_name='cellproduct',
            name='style',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cs_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.virtualuser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='secret',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='token',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
