version: '3'

services:
  gunicorn:
    build: 
      context: .
      dockerfile: ./gunicorn_Dockerfile
    image: gunicorn:20.1.0
    container_name: nosta_gunicorn
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=nosta.settings.production
    volumes:
      - .:/usr/src/app/
      - gunicorn:/var/run/gunicorn
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.17.7
    container_name: nosta_nginx
    depends_on:
      - gunicorn
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
      - ./static:/home/static
    ports:
      - 5500:80
  
  db:
    image: mariadb:10.6.4
    restart: always
    container_name: nosta_db
    environment: 
      MARIADB_ROOT_PASSWORD: nosta_db_root_password

    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  gunicorn:
    driver: local