version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./production_Dockerfile
    command: uwsgi --http :8000 --module nosta.wsgi 
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - prasic
      - nosta
    environment:
      - DJANGO_SETTINGS_MODULE=nosta.settings.production
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`nosta.${DOMAIN}`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.app.tls.certresolver=${CERT_RESOLVER}

  db:
    image: mariadb:10.6.4
    restart: always
    networks:
      - nosta
    environment:
      MARIADB_ROOT_PASSWORD: nosta_db_root_password
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  prasic:
    external: true
  nosta:
    external: true
