version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./production_Dockerfile
    command: uwsgi --http :8000 --module nosta.wsgi 
    container_name: app_sv
    depends_on:
      - db
    ports:
      - 5500:8000
    environment:
      - DJANGO_SETTINGS_MODULE=nosta.settings.production
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true

  db:
    image: mariadb:10.6.4
    restart: always
    container_name: db_sv
    environment:
      MARIADB_ROOT_PASSWORD: nosta_db_root_password
    volumes:
      - ./mysql:/var/lib/mysql
