version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: nosta_app
    networks:
      - prasic
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`nosta.${DOMAIN}`)
      - traefik.http.routers.web.entrypoints=https
      - traefik.http.routers.web.tls=true
      - traefik.http.services.web.loadbalancer.server.port=8000
      - traefik.http.routers.web.tls.certresolver=${CERT_RESOLVER}

volumes:
  mysql:

networks:
  prasic:
    external: true